
services:
  app:
    image: webdevops/php-apache-dev:8.2-alpine
    container_name: meu_projeto_app
    volumes:
      - ./src:/app
    ports:
      - "80:80"
    environment:
      - WEB_DOCUMENT_ROOT=/app/public
    networks:
      - app-network

  db:
    image: mysql:8
    container_name: meu_projeto_db
    ports:
      - "3306:3306"
    environment:
      - MYSQL_ROOT_PASSWORD=password
      - MYSQL_USER=user
      - MYSQL_PASSWORD=password
    volumes:
      - db_data:/var/lib/mysql
    networks:
      - app-network

volumes:
  db_data:

networks:
  app-network:
    driver: bridge